# Generated by Django 3.0.2 on 2020-01-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='no_of_actual_copies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='no_of_cuurent_copies',
            field=models.IntegerField(default=0),
        ),
    ]
