# Generated by Django 3.0.2 on 2020-01-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0003_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
